#include "ast.h"
#include "env.h"
#include "frontend.h"

// Headers generated by flex and bison.
#include "lexer.h"
#include "parser.h"

#include <stdio.h>
#include <glib.h>

int yyparse(void);

void done_parsing(GList* parse_result) {
      /* Save the AST root. */
}

int main(int argc, char** argv) {
      yyin = argc > 1? fopen(argv[1], "r") : stdin;

      if (yyparse()) {
            fprintf(stderr, "Error: failed to parse.\n");
            if (yyin != stdin) fclose(yyin);
            exit(EXIT_FAILURE);
      }

      /* Build the global environment, do typechecking. */

      if (yyin != stdin) fclose(yyin);
      yylex_destroy();
      exit(EXIT_SUCCESS);
}

