#include "ast.h"
#include "env.h"
#include "frontend.h"

// Headers generated by flex and bison.
#include "lexer.h"
#include "parser.h"

#include <stdio.h>
#include <glib.h>

int yyparse(void);
Env* prog_env;
GList * global_ast;

void done_parsing(GList* parse_result) {
      global_ast = parse_result; 
	  //printf("Hello there!!\n");
}

void build_environment(GList * node, Env * parent_env)
{
	GList * it = g_list_first(node);
	
	while(it != NULL)
	{
		struct decl * node = (struct decl *)it->data;
		
		//check type of decl
		if(symbol_is_fun(node->id))
		{
			//build local env, 
			Env * fun_env = env_new();
			//function parameters?
			//build_environment(node->type->fun.params, fun_env);
			
			//insert function env into parent env.
			printf("Look HERE: %d...", env_contains(parent_env, node->id));
			symbol_print(node->id);
			env_insert_fun(parent_env, node->id, node->type, fun_env, node->stmts);
			
			//other things for type checking (clash, set type of decl to be invalid)
			//printf("function\n");

			build_environment(node->decls, fun_env);
		}
		else
		{
			//build global declarations
			if(symbol_is_var(node->id)){
				printf("Symbol is VAR\n");
				env_insert(parent_env, node->id, node->type);
			}else if(symbol_is_field(node->id)){
				//env_insert(prog_env, symbol_field($1), $3);
				env_insert(parent_env, node->id, node->type);
				printf("Symbol is FIELD\n");
			}else if(symbol_is_fun(node->id)){
				printf("Symbol is FUN How did we get here?\n");
			}else if(symbol_is_typename(node->id)){
				printf("Symbol is Typename\n");
				env_insert(parent_env,node->id, node->type);
			}else if(!symbol_is_valid(node->id)){
				printf("Symbol is Invalid\n");
			}else{
				printf("Something went wrong and I have no SYMBOL for this\n");
			}
		}
		it = g_list_next(it);
	}
	
}

int main(int argc, char** argv) {
      yyin = argc > 1? fopen(argv[1], "r") : stdin;

	
	
      if (yyparse()) {
            fprintf(stderr, "Error: failed to parse.\n");
            if (yyin != stdin) fclose(yyin);
            exit(EXIT_FAILURE);
      }
      
      printf("\n");

      /* Build the global environment, do typechecking. */
      prog_env = env_new();
	build_environment(global_ast, prog_env);
	//call our function to print the prog environmnet
	decls_print_type(global_ast, prog_env);
	printf("\n");
	
	//env_print(prog_env);
      if (yyin != stdin) fclose(yyin);
      yylex_destroy();
      
      
      
      exit(EXIT_SUCCESS);
}




