#include "ast.h"
#include "env.h"
#include "frontend.h"

// Headers generated by flex and bison.
#include "lexer.h"
#include "parser.h"

#include <stdio.h>
#include <glib.h>

int yyparse(void);
Env* prog_env;
GList * global_ast;

void done_parsing(GList* parse_result) {
      global_ast = parse_result; 
	  //printf("Hello there!!\n");
}

void build_environment(GList * node)
{
	GList * it = g_list_first(node);
	
	while(it != NULL)
	{
		//check type of decl
		if(symbol_is_fun(((struct decl *)it->data)->id))
		{
			//build local env, function parameters, other things for type checking (clash, set type of decl to be invalid)
			printf("function\n");
			//build_environment(((struct decl *)it->data)->decls);
		}
		else
		{
			Symbol tmp = ((struct decl *)it->data)->id;
			//build global declarations
			if(symbol_is_var(tmp)){
				printf("Symbol is VAR\n");
			}else if(symbol_is_field(tmp)){
				printf("Symbol is FIELD\n");
			}else if(symbol_is_fun(tmp)){
				printf("Symbol is FUN\n");
			}else if(symbol_is_typename(tmp)){
				printf("Symbol is Typename\n");
			}else if(!symbol_is_valid(tmp)){
				printf("Symbol is Invalid\n");
			}else{
				printf("Something went wrong and I have no SYMBOL for this\n");
			}
		}
		it = g_list_next(it);
	}
	
}

int main(int argc, char** argv) {
      yyin = argc > 1? fopen(argv[1], "r") : stdin;

	
	
      if (yyparse()) {
            fprintf(stderr, "Error: failed to parse.\n");
            if (yyin != stdin) fclose(yyin);
            exit(EXIT_FAILURE);
      }
      
      printf("\n");

      /* Build the global environment, do typechecking. */
	build_environment(global_ast);
	
      if (yyin != stdin) fclose(yyin);
      yylex_destroy();
      
      
      
      exit(EXIT_SUCCESS);
}




